#ifndef PROJECTS_AXION_STRINGS_SETUP_H_
#define PROJECTS_AXION_STRINGS_SETUP_H_

namespace AxionStrings {

SLEDGEHAMR_ADD_SCALARS(Psi1, Psi2)
SLEDGEHAMR_ADD_CONJUGATE_MOMENTA(Pi1, Pi2)

}; // namespace AxionStrings

#endif // PROJECTS_AXION_STRINGS_SETUP_H_
