# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
# AMREX_HOME    ?=
SLEDGEHAMR_HOME ?= ../../../sledgehamr

# compiler
COMP      = gnu
USE_CUDA  = FALSE

# Optional debugging options.
DEBUG           = FALSE
USE_ASSERTION   = FALSE
FSANITIZER      = FALSE
MEM_PROFILE     = TRUE

include $(SLEDGEHAMR_HOME)/Make.sledgehamr
