# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
# AMREX_HOME 	?= 
SLEDGEHAMR_HOME ?= ../../../sledgeHAMR

# compiler
COMP      = gnu

# Optional debugging option within AMReX
DEBUG 		= FALSE
USE_ASSERTION 	= FALSE
FSANITIZER	= FALSE
MEM_PROFILE 	= FALSE
PROFILE 	= FALSE
TRACE_PROFILE 	= FALSE

include $(SLEDGEHAMR_HOME)/Make.sledgehamr
